g.ready(function(){g.setAnnotations([
{series : "value",x : 9,shortText : "B",text : "Bought at 9"},
{series : "value",x : 11,shortText : "S",text : "Sold from 9"},
{series : "value",x : 58,shortText : "B",text : "Bought at 58"},
{series : "value",x : 63,shortText : "S",text : "Sold from 58"},
{series : "value",x : 94,shortText : "B",text : "Bought at 94"},
{series : "value",x : 96,shortText : "S",text : "Sold from 94"},
{series : "value",x : 105,shortText : "B",text : "Bought at 105"},
{series : "value",x : 115,shortText : "S",text : "Sold from 105"},
{series : "value",x : 116,shortText : "B",text : "Bought at 116"},
{series : "value",x : 130,shortText : "S",text : "Sold from 116"},
{series : "value",x : 144,shortText : "B",text : "Bought at 144"},
{series : "value",x : 149,shortText : "S",text : "Sold from 144"},
{series : "value",x : 159,shortText : "B",text : "Bought at 159"},
{series : "value",x : 169,shortText : "S",text : "Sold from 159"},
{series : "value",x : 177,shortText : "B",text : "Bought at 177"},
{series : "value",x : 178,shortText : "S",text : "Sold from 177"},
{series : "value",x : 179,shortText : "B",text : "Bought at 179"},
{series : "value",x : 180,shortText : "S",text : "Sold from 179"},
{series : "value",x : 184,shortText : "B",text : "Bought at 184"},
{series : "value",x : 185,shortText : "S",text : "Sold from 184"},
{series : "value",x : 188,shortText : "B",text : "Bought at 188"},
{series : "value",x : 201,shortText : "S",text : "Sold from 188"},
{series : "value",x : 202,shortText : "B",text : "Bought at 202"},
{series : "value",x : 204,shortText : "S",text : "Sold from 202"},
]);});